### PR TITLE
William Kennedy's profile

### PR DESCRIPTION
**Pull request by ardan-bkennedy**

### CODE REVIEW

**Comment by dgryski** [comment]
Github link and avatar are taken from the file name.  This PR won't do what you expect.

**Comment by ardan-bkennedy** [comment]
Ok, so I need the name of the file to match a github account

**Comment by ardan-bkennedy** [comment]
I wish I knew how all this stuff worked. It appears this pull request include my new changes automagically.

**Comment by dgryski** [comment]
It's live now http://gophertown.org/goinggo

**Comment by ardan-bkennedy** [comment]
Awesome. Thanks for putting this together. Very Cool.

**Pull request merged**
